### ISSUE TITLE
Need proximity sensor turn off

### ISSUE THREAD

**Issue by grimer6261** [JDCTeam/issue_tracking_cm#13]
With some cases, the proximity sensor blacks out the screen and makes the phone inoperative. The turn of button in Settings is needed.

**Comment by smeroni68** [comment]
If a sensor is malfunctioning, the best thing to do is the fix of hardware problem.
Dusty or any other reason that block the proximity function can be solved by opening the phone (search on youtube video on how to procede... not really a difficult stuff on S4) and cleaning the sensor itself.
Is not the rom that must fix/avoid the problem.

**Comment by grimer6261** [comment]
Appreciate the reply, but that's not it. The case is waterproof, and
triggers the sensor do that the screen stays black. The stock ROM has a
setting to disable the sensor.

**Comment by sourlemon11** [comment]
I've also been having this issue. In addition, I've come directly from stock and the proximity sensor was working perfectly fine. When I check the default value under the proximity sensor it's at 255. I've tried changing it and recalibrating but the issue persists. 

EDIT: here is the [log](http://pastebin.com/S1eyRW11). It starts at around line 14 although I can't find anything that might be wrong. I think @grimer6261 is talking about when making a call, since I'm not able to unlock the screen to end the call. I've had to resort to using the power button (changed under settings) to end a call. I've also tested this with Sensor Box and the cover off. It could just be a problem with the calling app itself since the proximity sensor is working fine in the log.

**Comment by AntaresOne** [comment]
The proximity sensor is not used to lock/unlock device in this ROM if you don't install some kind of app from the Play Store.

You could do a test yourselves:
- remove any kind of cover/accessory (wanna be sure?) or just leave it on
- unlock device
- cover with a finger the two little balls on the right side of the earpiece

As you can see the screen **doesn't turn off**, therefore there is no bug here.

**Comment by grimer6261** [comment]
Sorry to disagree, but the proximity sensor is behind the earpiece. And as
I have tried to explain, it's not a bug, the sensor works properly, but
some cases cover the earpiece and only during a phone call does the problem
occur. The screen blacks out and stays black because the sensor turns of
the screen during the call. I didn't ask for a fix, I asked that the turn
off be included again.
