### ISSUE TITLE
Stuck with 'Network error'

### ISSUE THREAD

**Issue by seapython** [JDCTeam/issue_tracking_cm#44]
It seems possible to cause the UI of the phone (GT-I9505) to get stuck by holding the menu key down while WiFi and mobile data are off (but mine actually had no SIM card installed at the time).
This causes a 'Network error' pop-up and then it becomes impossible to recover from it without rebooting. Build OptimizedCM-12.1-20150817-jflte.

**Comment by B--B** [comment]
I' ve tried with a fresh install and stock launcher, UI doesn't stuck and nothing happens, no pop-ups and no freeze. If this happens in others launchers (proprietary) then this is not a cm bug.

**Comment by seapython** [comment]
I was using a clean install with nothing added or changed. Holding the menu key down seems to call 'Search' (I suspect), which then tries to get network access. It caused 'Network error' each time. The phone had _WiFi disabled_ and **no SIM card inserted**.
It may only happen if there is no SIM, which is why I specifically mentioned this detail above.

Other than this, I had STweaks crash every time while trying to start, but not initially and then not any more after installing some selected GApps. In the meanwhile I had enabled/disabled root access, played around etc, so can't be specific enough. Not sure I could reproduce. The system was still 100% unmodified at the time however.

The kernel is extremely fast, but graphic performance seemed to be noticeably inferior when compared with stock 5.0.1. I was testing chart plotting with opencpn, using a set of raster charts. Reasons other than graphics could however cause the same result, so can't specifically state that it is graphics and not file I/O, caching, RAM available, swapping policy etc. Especially as it got a bit better once the charts for the display area had been accessed once already, but still slower.

I wish the main 'Settings' were still tabbed like in 5.0.1, rather than dumped into one huge list now, but awesome ROM.

**Comment by B--B** [comment]
Already tried, this time with gapps installed and long pression of menù button works, search is called correctly, then the toast appears telling the user that there's no network available, no issues with stock launcher. STweaks does not work if you disable root. Regarding graphics performance i never seen less performance than Stock TW, you cannot compare two different OS because an app works better on TW without a good reason, if other apps works like in TW Rom then it' s related to the app or to the configuration of your phone

EDIT: Tabbed Settings are Sammy stuffs, AFAIK android and cm never had that

**Comment by seapython** [comment]
I will try and replicate the 'Network error' again for you on another phone, from a clean install. I more or less gave away the S4 I was using the other day. Someone is trying it out with this latest ROM at the moment.

STweaks gives out a message if started without root enabled. It did. It later crashed before displaying this message. It worked again after installing selected GApps. I don't understand why, only flagging this happened.
I will try to document a sequence leading to it, but no guarantee I can reproduce it again.

Regarding your comment about graphic performance, it is a negative. Apps can challenge many parts of the system concurrently and if the same code from the same app exhibits very different performance on two different systems, the root cause goes back to the system - it is the only thing that changed. A real-time interactive charting program is typically demanding not only in terms of graphics, but also file access and it would appear that something is bottlenecking it to some extent. The apparent outcome is reduced graphic performance, but there is nothing whatsoever saying that the root cause is indeed graphics and I thought I made this quite clear earlier.

Thanks for your comment about the tabbed settings, I didn't realise this. The tabbed settings are a good idea.

**Comment by B--B** [comment]
Even if you are able to replicate the bug it's obvious that the issue is not in the rom itself but to the related gapps package that you are using, and this is another story. We do not mantain gapps, other devs do it so this bug does not belong to us. Regarding STweaks, the app it's not related to gapps, and never crashed for me on both cm and aosp with supersu, same kernel and same stweaks repo sources. You haven't provided any logs or any relevant information, there' s the possibility that settings for Alucard kernel aren' t correctly loaded too if stweaks keeps crashing (and this could explain the poor 3d performance). Regarding your comment on graphic performance as i previously said: if 3d rendering works well on 99% of market apps probably the remaining 1% must update their code or are doing something wrong. Without a log i can't say anything else. And as you stated, you don't know what is causing this behaviour so... There's the possibility that your phone is not correctly configured too. You opened a bug without posting the necessary useful information, without posting a log and doing only suppositions on what could cause this behaviour. And regarding I/O performance i never had an issue with my extsdcard with Alucard kernel on both cm and aosp, just set the correct read-ahead value for your sdcard in STweaks, if files are in the external sdcard probably this will solve the problem.

**Comment by seapython** [comment]
As I wrote earlier, the 'Network error' bug occurred before anything else than the ROM was installed. This includes GApps.
Regarding performance matters, I can only invite you to also go back and read what I actually wrote again. It would have saved you from commenting on "graphic performance and 3D rendering". I also made no mention of any extSdCard. The files were on sdcard0.
I have flagged an issue with the information I had available. So far I haven't had a chance to try and replicate it from a clean install again.

**Comment by B--B** [comment]
Ok, now i'm tired of this, there are some rules to RESPECT here because this is a bug tracker, not an xda discussion. You haven't respected none of them, ok? Let me explain a thing: every message here means a mail to all the devs, that' s why we ask USEFUL information about your system and what you installed, that' why we ask for logs that you never provided, not your supposition. First thing: respect the rules means respect the devs that are working here all for free. We are glad to help, when there are the conditions for help people. And you provided none of them. Second thing: you talked about a network error bug, i' ve tried to reproduce and i wasn't able, with or without gapps, and you haven't provided a log as requested. Then you started to complain about STweaks, because crashes but works for 99.9% users with same app sources and same kernel, cm slim and aosp, obviously without a log. After that, you started to complain about poor graphic performance on an app, and all the rest works fine. And this time a log? Obviously not. Even if i misunderstood your message, nothing changes, the answer is the same. And i told you before. Without a log there' s nothing that we can do and nothing else i can say. Regardind external sd, i wrote "if" because i'm trying to understand what you should have told us in your first message. And no need to save no one mate, i answered you because i' m working now on aosp, i'm more interested in issues and bugs regarding the rom that actually i'm mantaining, but if i can i try to help here so... Sorry if i forgot the exact reason or your issue but i've better things to do in my life, i remembered that was something regarding the graphics, and i haven't read again the previous message, because without a log i will never understand what's wrong in your phone in every case. Next time provide the info requested in the main page. Thanks.

**Comment by AntaresOne** [comment]
@seapython no important informations provided as for the README and no answer after a month, issue closed.
