### ISSUE TITLE
Touchscreen not responding when unlocking device

### ISSUE THREAD

**Issue by Zbiba1** [JDCTeam/issue_tracking_cm#5]
Hi, 
I have a problem, when I try to unlock the device the touchscreen just won't respond sometimes. Not quite sure what info you need to help you troubleshoot the problem.

Using it on I337M (had the 5.0.2 version before without any problem)

**Comment by juansvc** [comment]
Have the same problem.

**Comment by Zbiba1** [comment]
Ok so since we have no answer, I can tell you it's a kernel issue. Tried this kernel with another rom and it was exactly the same problem you should just use another kernel. I'm using sabermod from jun7th it's most stable one.

**Comment by smeroni68** [comment]
Can you link the kernel you tested without the touch problem?
Not the file but the thread on xda... thanks.

**Comment by Zbiba1** [comment]
http://forum.xda-developers.com/galaxy-s4/i9505-develop/rom-cyanogenmod-11-built-justarchi-t2846082

**Comment by B--B** [comment]
You get no answer because you posted nothing useful, like a log. We are a team, but not all of us works on cm, so without useful information the issue that you opened is completely unuseful. I can't reproduce this on my test phone, and i don't think it's related to kernel. AOSP use Alucard kernel and none of AOSP users had this bug in a month.

**Comment by smeroni68** [comment]
The link you posted ia a CM11... here we are on 12.1...

**Comment by Zbiba1** [comment]
@smeroni68 Open the link... It's based on 12.1

@B--B  did not mean any disrespect. I was just updating the post for others who may have encountered the same issue. I know yiu guys work hard on these roms. The thing is I did not get any answer for a week and it was kind of a big issue since it made impossible to answer calls sometimes. 

It's true I did not provide much info but as I said I wasn't sure what you needed (I have read the OP's posts). I tried troubleshooting on my own and after changing rom it solved the problem for me, and when I flashed this kernel on the new rom it came back... My conclusion kernel issue. I may be wrong tho, I'm pretty new at this and still learning.

Again sorry if I sounded like a jerk really wasn't my intention.

**Comment by smeroni68** [comment]
The compiling toolchain are responsible for the complete rom results... the alu kernel in our roms is the same 100%... only ramdisk are different. 
The issue you and other reported is not affecting our phones, so if no logs or other info are given...  we can't reproduce the problem... how can we analyse and understand?

**Comment by Zbiba1** [comment]
Yes I do understand that I did not provide enough infos but as I said I did not know what infos you needed and no one replied until now. As I said tho, I know it is my fault for not giving the logs but I did not know how to proceed. 

As I said, maybe I did something wrong each time I tried to flash it or maybe I skipped a step, I'm still new at this. I'll give it a try again as soon as I have some time. I just wanted to share my experience with the others having this issue.

**Comment by smeroni68** [comment]
If you like, try the AOSP rom... do a full clean installation and check about the issue... this is a suggestion.
I have 2 phones: CM Optimised and AOSP... both works perfectly.
Both roms has the same Kernel, so if something happens different, can be on rom side. 
We develop actively AOSP... CM is based on CM sources and now we do not put too much effort on this side...
On the other side you can use the rom you like, so if the one from Synergy510 is good for you, you can use it.

**Comment by WtGuy** [comment]
Hello,

This is a bit of a necro post, but I am also having this issue. Please see the the details below:

Phone model: SGH-1337M
Baseband version: 1337MVLUGOC4
ROM version: 20150817

GApps Package: Open GApps Nano 20150831

Did you do a clean install for the currently installed build? yes
Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no

Attached is my logcat from the most recent occurence. I intentionally turned my device off at 11:21 system time and turned it on to unlock at 11:22 system time. At the time of turn on, I was unable to use the touchscreen at all.

Please let me know if you need anymore details.
Logfile: http://pastebin.com/DPBc9giZ

**Comment by Qbax7** [comment]
Hi.
I have same issue as WtGuy and Zbiba1 but my phone is i9505.
When I try to unlock the device the touchscreen just won't respond at all ;(

I try  [JDCTeam][STABLE][5.1.1][22 October] Optimized CyanogenMod 12.1 builds and 
[JDCTeam][STABLE][5.1.1][RRO][20 October] The Android Open Source Project.

I'v never done a logcat so correct me if I did't bad.

Logcat: http://pastebin.com/JrWyAa7x

Sorry 4 bad English.

Ps.
I'm on SaberMod CM12.1 for Jflte - Build Oct 24, 2015 at this moment and works like a charm. Bug is not there ;)

**Comment by AntaresOne** [comment]
@WtGuy @Qbax7 please get the kmesg when it happens, if you don't know what it is just install syslog app from the play store.

@Qbax7 your last sentence is not going to help as its kernel is a modified CM one while our is completely different :+1:

**Comment by Revile77** [comment]
Hi everyone,

Found this issue while searching for a solution to the exact same problem. On bootup the screen works, however after first wake from deep sleep (regardless of whether this is caused by a notification or a pressed power button to manualy wake the device), the screen is no longer responding to touch.

Device: GT-I9505
Baseband: I9505XXUHOB7
ROM tested on: Optimized CM12.1 builds 22 Oct and 01 Nov

I've also tried the CM kernel from SaberMod CM12.1 on these Optimized CM builds and the issue does not appear, so that IMO suggests that this is Alucard kernel related issue.

I have extracted the kmesg log. There are two of them:

kmsg1.log : http://pastebin.com/7LqM6jLA
Contains a log from boot until I enter PIN code, let the phone into deep sleep and then wake it - at this point the screen no longer works.

kmsg2.log : http://pastebin.com/CBTZhMQK
Log from subsequent attempts, when waking the phone and then putting it into sleep again.

I hope there is something useful in those logs.

**Comment by ghost** [comment]
I first came upon JDCTeam's ROM in July, 2015. I used the July and August versions with the touchscreen half the time not responding during any attempt to wake my phone. With, without GApps, clean or dirty, the issue persisted but after turning on/off the screen many times via power button and then trying it'd work. In the October and November builds, it never works after locking for the first time. Even during phone setup from a clean wipe, with and without GApps. CyanogenMod works fine, 100%.

I apologize I can't be more helpful other than mentioning I have an I337 model from Cricket ("AT&T"). If a developer would like more information I'd be happy to provide any information, if told how to get it.

I can't seem to find the July/August builds. If anyone can provide a link, I'd most appreciate it.

(I used OTAUpdates to reach the August build, but it kept trying to present that update even after installing and telling it to ignore it.) 20150817 is the last I used that half-worked.

Phone model: SGH-I337
Baseband version: I337ZTUUBOA1
ROM version: 20151101

GApps Package: None/Any (Many attempted)

Did you do a clean install for the currently installed build? yes
Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no

**Comment by suarez-agu** [comment]
@AntaresOne 

Hey I just want to let you know that I have been having the same issue where touchscreen when locking the phone doesn't work. It doesn't matter if its at first boot or at the 300th.

I think this problem is related to the I337 model. I have a Canadian (Fido) SGH-I337 model

I can't post logs at the moment and will do ASAP. 

I would just like to know what you think of all this.

Thanks a lot for all the work you do in all of this

**Comment by ghost** [comment]
The issue was half-bad in 817 but is capable of fixing itself, almost like a race-condition in code. Button lighting activation (even for 'always on') in these versions seems very inconsistent.

**Comment by RichardoC** [comment]
I also have this issue with an i9505 using both of the following roms

https://romhut.com/roms/Optimized-CM-121
http://forum.xda-developers.com/galaxy-s4/i9505-orig-develop/rom-cyanogenmod-12-t2943934

Which logs would help trace this?

**Comment by ravv7** [comment]
I have the same problem, touch screen do not respond when ulocking (swipe) after some time, it works eg half  a day and then one moment not. It is possible just swith the phone off with holding power button.
Device: GT-I9505
Baseband: I9505XXUHOF2
ROM tested on: Optimized CM12.1 builds 22 Oct and 01 Nov
with several nightly builds works fine

Did you do a clean install for the currently installed build? yes for 22OCt, manual update 01Nov
Did you reboot after having the issue? yes - it is possible just swith the phone off with holding power button
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no 

g-apps micro

What log should I send, when I must switch off phone and switch it on again?

update:
So it happened again. After power off/n here is syslog
http://mujweb.cz/rav/cm/2015-11-19_18.08.zip

**Comment by BigVner** [comment]
I have the same problem on my I9505. It can be really anoying :/

**Comment by Andrei173** [comment]
I have the same problem that @Slus , @YujiSaeki and @Revile77 has. Touchscreen won't work after  unlocking the device for the first time. Hardware buttons work, power button works, but the screen does not. This is an issues even with the latest build (18 Ian) doing a clean install. 
I'm sorry I can't provide logs, I simply don't know how at this point. What I can tell you in addition to this is that if I flash the CM-Kernel_20151130 provided on RomHut  ( https://romhut.com/roms/Optimized-CM-121 ), the issues goes away completely. The reason I'm reporting this is that with that aforementioned CM-Kernel, the battery does drain relatively fast.

**Comment by ghost** [comment]
@Andrei173 I suspected it was the release but with no progress and an aging phone I was considering a Nexus 6P to just have some of the nicest and newest. I had a feeling it broke around November.

**Comment by BobDodds** [comment]
I am trying this rom and gapps micro, after using many cm 12.1 nightlies on this unlocked i337, on cricket att.

This version rom 20160118 blocks all touch events after coming back from the first sleep, whether sleep init by timeout or power switch. I turned screen lock to none. I turned Ambient Display off. The only thing that can bypass the problem is staying on usb or charger cable. I made sure Devel option to block touch events to apps is Off. I even tried the On position. I can't think of anything else to try to let touch events through after returning from sleep. There's no lock, not even swipe lock. I'll go ahead and try swipe lock, just to nail all possibilities. OK, tried swipe lock on, no help.

Nightlies would have bluetooth share crashing. I haven't seen bluetooth share crash on here yet. I went into Settings, Apps, Running, Bluetooth Share and STOPped the Pbap service--contacts access--that helps on nightlies with this. I drove car with power cable, preventing screen off, and the rom worked well and bluetooth stayed on for half an hour.

I may try the gapps-nano which says something about Swype libs when it installs with nightlies, to see if it helps the touch events persist past first screen off.

**Comment by zeule** [comment]
Had the problem with  I9505 when was using AntaresOne's builds a year ago. Today installed TWRP from JDCTeam and Optimized CM. Both showed the problem: touchscreen does not work after screen goes off in CM, and after some time in TWRP. I could try to bisect the kernel, but what repository and branch do I need to test?
