### ISSUE TITLE
Screen rotation & adaptive brightness not working 

### ISSUE THREAD

**Issue by aphidii** [JDCTeam/issue_tracking_cm#6]
Have auto rotate, and auto brightness enabled but neither work.
The brightness issue kills battery

Baseband i9507XXUENB5
Not sure what logs you need, just let me know.

**Comment by aphidii** [comment]
Also noticed Android System is topping battery drain but wakelock detector isn't reporting any CPU wakelocks

**Comment by aphidii** [comment]
Battery drain pics: http://imgur.com/a/Kkk1S

**Comment by aphidii** [comment]
Further to the battery drain issue, excessive battery drain only occurs while the device is awake. No wakelocks. I've ruled out location settings, the launcher and install method as culprits

**Comment by smeroni68** [comment]
I see the screens you posted... but what you expect from the device awake and screen on?

**Comment by aphidii** [comment]
i expect it to drain at a reasonably equal rate to cm12 jflte optimized. I'm getting maybe 60% the screen on time i was with 5.0.

**Comment by smeroni68** [comment]
How old is your battery?

If you accept a suggestion, buy one of these: http://www.amazon.it/gp/product/B00CBTTA4A?psc=1&redirect=true&ref_=oh_aui_detailpage_o02_s00

**Comment by aphidii** [comment]
it is 2 years old, i know a new battery will improve my battery life.

regardless of battery age, I am still getting less screen on time by a significant amount (close to half) than i was on 5.0 jflte optimized by alucard & antaresone

i don't expect a quick fix, i'm just trying to help by reporting it and giving as much info as i can.

**Comment by smeroni68** [comment]
Mate... your battery is gone... 2 years for a battery is quite a century... that's why I suggested you to buy another one. ANKER quality is really huge... the cells are of first class (I bought many for different phones and never had to complain about).

Accept my suggestion... and you will close by yourself this "issue" because you will see the reason of the drain.

Regards

**Comment by smeroni68** [comment]
FYI: I have three S4 phones (2x GT-I9505 and 1x GT-I9506).
I have 7 batteries (3x SAMSUNG Originals and 4x ANKER).

I always used to rotate the battery, so when a battery is low, remove it and put another one full charged (I use two external battery charger).
Of these 7 batteries, 2 are nearly gone: an ORIGINAL one and an ANKER (both has 2 years life).

You know why I'm sure about that?

Because when you use a phone and you know what's the normal discharge time/duration of it, when you insert a "bad" battery, the time is lower than 30% to 50%... if you have only 1 battery, you just feel the drain as if is related to ROM... but that's wrong.

Did you have an old backup of CM12? I hope yes... backup your current installation and restore for a day the CM12... I expect the same behaviour you found on latest. In this case you can understand what I'm telling you.

Regards

**Comment by aphidii** [comment]
Why be so horrible about it?
I have rolled back to cm12 and it is back to regular battery life.
Android System is no longer draining the same amount of battery as the display. if you don't believe me that Android System is running something while the phone is awake and draining a large amount of battery then that is your problem.
thanks for absolutely nothing, I'll close this thread now as it is clear you have nothing to add here and i'll maybe try your rom some months in the future.

**Comment by smeroni68** [comment]
OK... as you desire...

**Comment by B--B** [comment]
It's non a matter of "believe" or not.. The problem is that this is a issue/bug tracking, not xda, there isn't nothing useful in your post, and nothing that can help us to discover what' s going on, that' s all. This is git, not xda, a dev board for devs and tester that at least knows how to send useful information to devs. if someone doesn't know how to pick/post correctly a log the issue opened should be closed immediatly, like ubuntu launchpad bugs do and all other bug tracker do. And everyone of us has a real life, sorry but we have no time to explain how to pick logs and send useful information when you can learn by yourself googling a bit. So you should say thanks to Stefano... At least for the patience.
