### ISSUE TITLE
Cannot make or receive calls. reboots to logo

### ISSUE THREAD

**Issue by deadlyizzy** [JDCTeam/issue_tracking_cm#98]
Phone model: GTI9505
Baseband: I9505XXUHPF3
ROM version OptimizedCM-13-20160718
[Gapps:]) open_gapps-arm-6.0-aroma-20160722.zip

I've followed every step, so yes I did a clean install.

I did a boot several times after the problem began.

No I did not flash another kernel.

No I did not install Xposed.

No I do not have SuperSu related issues.

Hi,

I'm having problems with calls. I cannot make or receive calls. It reboots. If I try to go in the phone settings, it crashes. Can someone help me with this?

[2016-07-22_16.29.zip](https://github.com/JDCTeam/issue_tracking_cm/files/378932/2016-07-22_16.29.zip)

**Comment by B--B** [comment]
07-22 16:13:55.101 E/AndroidRuntime(24106): FATAL EXCEPTION: main
07-22 16:13:55.101 E/AndroidRuntime(24106): Process: com.google.android.dialer, PID: 24106
07-22 16:13:55.101 E/AndroidRuntime(24106): Theme: themes:{default=overlay:com.blissroms.moelle.ddoverhauled, iconPack:com.blissroms.moelle.ddoverhauled, fontPkg:com.blissroms.moelle.ddoverhauled, com.android.systemui=overlay:com.blissroms.moelle.ddoverhauled, com.android.systemui.navbar=overlay:com.blissroms.moelle.ddoverhauled}
07-22 16:13:55.101 E/AndroidRuntime(24106): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.dialer/com.google.android.dialer.settings.GoogleDialerSettingsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.app.ActivityThread.-wrap11(ActivityThread.java)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.os.Handler.dispatchMessage(Handler.java:102)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.os.Looper.loop(Looper.java:148)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.app.ActivityThread.main(ActivityThread.java:5461)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at java.lang.reflect.Method.invoke(Native Method)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-22 16:13:55.101 E/AndroidRuntime(24106): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:340)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at com.android.dialer.settings.AppCompatPreferenceActivity.setContentView(AppCompatPreferenceActivity.java:66)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:557)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at com.android.dialer.settings.AppCompatPreferenceActivity.onCreate(AppCompatPreferenceActivity.java:41)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at com.android.dialer.settings.DialerSettingsActivity.onCreate(DialerSettingsActivity.java:44)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.app.Activity.performCreate(Activity.java:6251)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
07-22 16:13:55.101 E/AndroidRuntime(24106):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)

Try removing your theme

Ps: Seems that Google Dialer is your issue, and it's not a part of cm..

**Comment by deadlyizzy** [comment]
So stupid of me. Thank you. After I reboot it resolved the issue
